# Generated by Django 3.1.3 on 2021-05-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20210506_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='course',
        ),
    ]
